#include "src/cocoa_time.c"
#include "src/cocoa_init.m"
#include "src/cocoa_joystick.m"
#include "src/cocoa_monitor.m"
#include "src/cocoa_window.m"
#include "src/nsgl_context.m"
#include "src/context.c"
#include "src/egl_context.c"
#include "src/glx_context.c"
#include "src/init.c"
#include "src/input.c"
#include "src/linux_joystick.c"
#include "src/monitor.c"
#include "src/osmesa_context.c"
#include "src/platform.c"
#include "src/posix_module.c"
#include "src/posix_poll.c"
#include "src/posix_thread.c"
#include "src/posix_time.c"
#include "src/vulkan.c"
#include "src/wgl_context.c"
#include "src/win32_init.c"
#include "src/win32_joystick.c"
#include "src/win32_module.c"
#include "src/win32_monitor.c"
#include "src/win32_thread.c"
#include "src/win32_time.c"
#include "src/win32_window.c"
#include "src/window.c"
#include "src/wl_init.c"
#include "src/wl_monitor.c"
#include "src/wl_window.c"
#include "src/x11_init.c"
#include "src/x11_monitor.c"
#include "src/x11_window.c"
#include "src/xkb_unicode.c"

#define fitToMonitor null##fitToMonitor
#define acquireMonitor null##acquireMonitor
#define releaseMonitor null##releaseMonitor
#define createNativeWindow null##createNativeWindow
#include "src/null_init.c"
#include "src/null_joystick.c"
#include "src/null_monitor.c"
#include "src/null_window.c"
